import { isStoreCollectableOrder } from '../../../../shared/platforms/payment-coverage';

export type EditablePaymentMethod = 'cash' | 'card';

export interface EditablePaymentRouteRow {
  id: string;
  method: EditablePaymentMethod;
  amount: number;
  currency?: string | null;
  transactionRef?: string | null;
}

export type PaymentEditRoute =
  | { kind: 'blocked'; reason?: 'adjusted' | 'platform_held' | 'provider_owned' }
  | { kind: 'collect-missing' }
  | {
      kind: 'edit-existing';
      currentMethod: EditablePaymentMethod;
      payments: EditablePaymentRouteRow[];
    };

interface PaymentEditOrderLike {
  id?: unknown;
  status?: unknown;
  payment_status?: unknown;
  paymentStatus?: unknown;
  payment_method?: unknown;
  paymentMethod?: unknown;
  plugin?: unknown;
  platform?: unknown;
  external_plugin_order_id?: unknown;
  externalPluginOrderId?: unknown;
  ghost_metadata?: unknown;
  ghostMetadata?: unknown;
}

interface PaymentEditBridgeLike {
  payments: {
    getOrderPayments(orderId: string): Promise<unknown>;
  };
}

interface PaymentEditRowLike {
  id?: unknown;
  method?: unknown;
  status?: unknown;
  amount?: unknown;
  currency?: unknown;
  transactionRef?: unknown;
  paymentOrigin?: unknown;
  payment_origin?: unknown;
  terminalDeviceId?: unknown;
  terminal_device_id?: unknown;
  transaction_ref?: unknown;
  refundedAmount?: unknown;
  refunded_amount?: unknown;
  remainingRefundable?: unknown;
  /** Native proof from original columns, metadata and provider-attempt history. */
  isProvenManualOriginal?: unknown;
  /** The server refused this till payment as platform-held money (R4). */
  platformHeldSetAside?: unknown;
}

const normalized = (value: unknown): string =>
  String(value ?? '').trim().toLowerCase();

const asEditableMethod = (value: unknown): EditablePaymentMethod | null => {
  const method = normalized(value);
  return method === 'cash' || method === 'card' ? method : null;
};

const textOrNull = (value: unknown): string | null =>
  typeof value === 'string' ? value : null;

/**
 * Does the delivery platform hold this order's money (shared rule R4, round
 * 3 review 01/10/2026)? Its disposition says so (the shared
 * `isStoreCollectableOrder`, as the till's collection refusal reads it), or
 * the server refused a till payment on it as platform-held. Such an order's
 * money is never collected or recorded at the till: its record is the
 * platform's settlement, restored from the server.
 */
export function orderMoneyIsPlatformHeld(
  order: PaymentEditOrderLike,
  paymentRows: readonly PaymentEditRowLike[],
): boolean {
  if (paymentRows.some((row) => row.platformHeldSetAside === true)) return true;
  return !isStoreCollectableOrder({
    id: String(order.id ?? ''),
    platform: textOrNull(order.plugin ?? order.platform),
    externalPlatformOrderId: textOrNull(
      order.external_plugin_order_id ?? order.externalPluginOrderId,
    ),
    ghostMetadata: order.ghost_metadata ?? order.ghostMetadata ?? null,
  });
}

export function routePaymentEdit(
  order: PaymentEditOrderLike | null | undefined,
  paymentRows: readonly PaymentEditRowLike[],
): PaymentEditRoute {
  const route = routeLedgerPaymentEdit(order, paymentRows);
  // Shared rule R4: the platform's money is never collected or recorded at
  // the till. Symptom before (round 3 review, 01/10/2026): a platform-held
  // order with a pending or partly paid label and no till row was routed to
  // "collect the missing payment" in cash or card; only the till's write
  // refused it (when the disposition was known), or the server refused it
  // again and it was set aside again.
  if (route.kind === 'collect-missing' && order && orderMoneyIsPlatformHeld(order, paymentRows)) {
    return { kind: 'blocked', reason: 'platform_held' };
  }
  return route;
}

export function isManualEditableReceipt(row: PaymentEditRowLike): boolean {
  const method = normalized(row.method);
  const origins = [row.paymentOrigin, row.payment_origin].map(normalized).filter(Boolean);
  const devices = [row.terminalDeviceId, row.terminal_device_id];
  if (devices.some(value => String(value ?? '').trim()) || !['cash', 'card'].includes(method)) return false;
  const explicitManual = origins.length > 0 && origins.every(origin =>
    ['manual', 'manual_card', 'manual_recovery'].includes(origin),
  );
  if (origins.length > 0 && !explicitManual) return false;
  const references = [row.transactionRef, row.transaction_ref]
    .map(value => String(value ?? '').trim()).filter(Boolean);
  // CARD timestamps are generated by the local manual-card flow. Require its
  // stored provenance; a reference or a customer's platform label is no proof.
  if (references.some(reference => !/^CASH-[0-9]+$/.test(reference)
    && !(explicitManual && /^CARD-[0-9]+$/.test(reference)))) return false;
  return explicitManual || method === 'cash' || references.some(reference => /^CASH-[0-9]+$/.test(reference));
}

function isFullyReturnedManualHistory(paymentRows: readonly PaymentEditRowLike[]): boolean {
  const cents = (value: unknown): number | null => {
    if (typeof value !== 'number' || !Number.isFinite(value) || value < 0) return null;
    const scaled = value * 100;
    const rounded = Math.round(scaled);
    return Number.isSafeInteger(rounded) && Math.abs(scaled - rounded) < 1e-7 ? rounded : null;
  };
  return paymentRows.length > 0 && paymentRows.every((row) => {
    const amount = cents(row.amount);
    return typeof row.id === 'string' && row.id.trim().length > 0
      && row.isProvenManualOriginal === true
      && isManualEditableReceipt(row)
      && ['refunded', 'completed'].includes(normalized(row.status))
      && amount !== null && amount > 0
      && cents(row.refundedAmount) === amount
      && row.remainingRefundable === 0;
  });
}

function routeLedgerPaymentEdit(
  order: PaymentEditOrderLike | null | undefined,
  paymentRows: readonly PaymentEditRowLike[],
): PaymentEditRoute {
  if (!order) return { kind: 'blocked' };

  const orderStatus = normalized(order.status);
  if (
    orderStatus === 'cancelled' ||
    orderStatus === 'canceled' ||
    orderStatus === 'refunded'
  ) {
    return { kind: 'blocked' };
  }

  const completedPayments = paymentRows.flatMap((row) => {
    const id = String(row.id ?? '').trim();
    const method = asEditableMethod(row.method);
    if (normalized(row.status) !== 'completed' || !id || !method || !isManualEditableReceipt(row)) return [];

    return [
      {
        id,
        method,
        amount: Number(row.amount ?? 0),
        currency: textOrNull(row.currency),
        transactionRef:
          typeof row.transactionRef === 'string' ? row.transactionRef : null,
      } satisfies EditablePaymentRouteRow,
    ];
  });

  const paymentStatus = normalized(
    order.payment_status ?? order.paymentStatus ?? 'pending',
  );

  // Restoring an order never restores its returned money. This opens only a
  // NEW collection, whose caller still reads native settlement/generation;
  // none of the adjusted originals may enter the tender-editing path.
  if (orderStatus === 'pending' && paymentStatus === 'pending'
    && isFullyReturnedManualHistory(paymentRows)) {
    return { kind: 'collect-missing' };
  }

  if (
    paymentStatus === 'refunded' ||
    paymentStatus === 'voided' ||
    paymentStatus === 'cancelled' ||
    paymentStatus === 'canceled'
  ) {
    return { kind: 'blocked' };
  }

  if (paymentStatus === 'partially_paid') {
    return { kind: 'collect-missing' };
  }

  // The native ledger forbids rewriting tender history after an adjustment.
  // Check all rows, including refunded rows filtered out of the editable list.
  // A payment set aside for review (`duplicate_review`) holds the order the
  // same way: its tender is decided on the Z, never by a method edit.
  if (paymentRows.some((row) =>
    ['refunded', 'voided', 'duplicate_review'].includes(normalized(row.status)) ||
    Number(row.refundedAmount ?? row.refunded_amount ?? 0) > 0,
  )) {
    return { kind: 'blocked', reason: 'adjusted' };
  }

  if (completedPayments.length > 0) {
    return {
      kind: 'edit-existing',
      currentMethod:
        completedPayments[0]?.method ??
        asEditableMethod(order.payment_method ?? order.paymentMethod) ??
        'cash',
      payments: completedPayments,
    };
  }

  if (paymentRows.some(row => normalized(row.status)==='completed' && !isManualEditableReceipt(row))) return { kind:'blocked', reason:'provider_owned' };
  if (paymentRows.length > 0) return { kind: 'blocked' };

  return paymentStatus === 'pending' || paymentStatus === 'partially_paid'
    ? { kind: 'collect-missing' }
    : { kind: 'blocked' };
}

export async function loadPaymentEditRoute(
  bridge: PaymentEditBridgeLike,
  order: PaymentEditOrderLike | null | undefined,
): Promise<PaymentEditRoute> {
  const orderId = String(order?.id ?? '').trim();
  if (!order || !orderId) return { kind: 'blocked' };

  const paymentRows = await bridge.payments.getOrderPayments(orderId);
  if (!Array.isArray(paymentRows)) return { kind: 'blocked' };
  return routePaymentEdit(order, paymentRows);
}
